issue#12/payments-infrastructure
bcc-code/bcc-pay pull request #13
Opened 2021-07-23 13:44 UTC by markiyanshvets

Integration with nets client;

https://github.com/bcc-code/bcc-pay/issues/12

2021-07-27 15:51 UTC, yuriy-butkevych commented on Api/BccPay.Core.Infrastructure/PaymentModels/NetsNodes/Charge.cs
> +    using System.Collections.Generic;
?

2021-07-27 15:51 UTC, yuriy-butkevych commented on Api/BccPay.Core.Infrastructure/PaymentModels/NetsNodes/CheckoutOnCreate.cs
> +    using System.Text.Json.Serialization;
new code style? :)

2021-07-27 15:55 UTC, yuriy-butkevych approved these changes

2021-07-27 16:16 UTC, markiyanshvets commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentPrivatePersonRequest.cs
> +    public class CreatePaymentPrivatePersonRequest
done

2021-07-27 16:16 UTC, markiyanshvets commented on Api/BccPay.Core.Infrastructure/PaymentModels/NetsNodes/CheckoutOnCreate.cs
> +    using System.Text.Json.Serialization;
removed

2021-07-27 16:37 UTC, tkristiansen requested changes
I've added some comments. Overall, I think we need to be able to create / register the payment in our system before the payment method / provider is selected. Reasons:

* We need to have the amount and currency known in order to select the payment method in the UI
* We haven't really defined this, but @oskarpbcc brought it up and I believe we should allow to switch to another payment method without generating a new payment ID if the payment is failing.
 
This also means that the values that are specific to a payment attempt or payment provider should be kept in a list.

Suggestion: We add PaymentAttempt as class where all the payment method / attempt specific data is stored. We have a `PaymentAttempt CurrentAttempt` property on the payment and also a list `List<PaymentAttempt> FailedAttempts` on the Payment entity. If CurrentAttempt fails and we want to start a new attempt, we can add the failed attempts to FailedAttempts and create a new CurrentAttempt. 

This would then require to also have a Guid ID for the PaymentAttempt and use that towards the payment providers rather than the Payment itself.

These are just ideas that we can also discuss further.. In any case, I'm seeing the need for supporting multiple attempts and also to register the payment before we do a payment attempt. The question is only how to model it...

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentRequest.cs
> +        public Guid PayerId { get; set; }
Samvirk is using GUID for contacts, meaning that it is easy and good for us to limit this to Guid. But maybe other systems use an integer or other string as ID. For them it would be easier to use this library if PayerId was just a string, since the id can then map one to one... Would there be any drawback of opening up the type to allow any string? Maybe add some sort of configurable rules / validation if we want to validate that the ID is currently a GUID?

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentRequest.cs
> +        /// For Nets provider : Currency should always be specified using a 3-letter code (ISO-4217).
Not only for Nets provider - we should also always use (upper case) 3-letter codes.

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentRequest.cs
> +        public int Amount { get; set; }
I suggest that we use ```public decimal Amount { get; set; }``` in our general model and then we can convert to Nets format when mapping to Nets.

That means we would be saving e.g. 10.24 rather than 1024 when we have 10.24 NOK.

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> +                // TODO: Depend on payment provider
We should have one uniform model for our payments and then map to what the provider uses when sending the data to the provider. I have no strong opinion which one to use, but we should pick one and stick to it :-)

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> +                    .Matches(new Regex(@"^([0-9]{1,9})$"));
There are postal codes (in UK etc.) that have letters as well. I think we should allow at least 0-9, A-Z and spaces.

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> +                return countryCode.Length == 3;
maybe check that it is upper case as well, or convert to upper case.

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Domain/Entities/Payment.cs
> +        public DateTime Updated { get; set; }
Updated should probably be nullable?

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Domain/Entities/Payment.cs
> +        public int Amount { get; set; }
I suggest to use decimal instead of int in our internal model.

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Domain/Entities/Payment.cs
> +            Updated = DateTime.Now;
Ok, if Updated is always set it will also work. I would prefer to have it null, though, as you can then more easily see if there has been an update...

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Enums/PaymentMethod.cs
> +        CreditCard
I suggest to give this payment method the "technical name" NetsCreditCard (we might have MollieCreditCard as well). Towards the users, we just present it as Credit card (and we should never have NetsCreditCard and MollieCreditCard activated for the same currencies).

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Infrastructure/PaymentProviders/Implementations/CreditCardPaymentProvider.cs
> +    internal class CreditCardPaymentProvider : IPaymentProvider
NetsCreditCardPaymentProvider

2021-07-27 16:37 UTC, tkristiansen commented on Api/BccPay.Core.Shared/Converters/PhoneNumberConverter.cs
> +            return (prefix, normalizedNumber[prefixDigitsLength..]);
Maybe only skip the prefix if the number actually starts with the prefix? 

My full Norwegian number is +47 919 29 206. It is common to enter only 91929206, and if I read this code correctly, you would then not fail but rather just return +47 as prefix and 929206 as number..

2021-07-28 07:47 UTC, markiyanshvets commented on Api/BccPay.Core.Shared/Converters/PhoneNumberConverter.cs
> +            return (prefix, normalizedNumber[prefixDigitsLength..]);
is it would be good to request a phone with two fields - prefix and national number?

Because we need this representation in NetsProvider and there is a lot of patterns for country prefix and we can't, actually, handle any format given by the requested API

2021-07-28 07:55 UTC, markiyanshvets commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentRequest.cs
> +        /// For Nets provider : Currency should always be specified using a 3-letter code (ISO-4217).
Here I thinking about the list of currencies supported by API, maybe we should add it and update it in the future? Also, we have validation on the provider side

2021-07-28 08:33 UTC, tkristiansen commented on Api/BccPay.Core.Shared/Converters/PhoneNumberConverter.cs
> +            return (prefix, normalizedNumber[prefixDigitsLength..]);
We don't need to support everything - we can expect +47 919 29 206, only take digits, strip leading zeros and then verify that the number starts with the country prefix. If it does not start with the country prefix, the number is invalid. Agree?

2021-07-28 08:35 UTC, tkristiansen commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentRequest.cs
> +        /// For Nets provider : Currency should always be specified using a 3-letter code (ISO-4217).
Not fully sure what you mean. I just wanted to say that the comment "For Nets provider : " could be skipped / or we should add that the same rule applies for our BCC Pay in general..

2021-07-28 08:40 UTC, markiyanshvets commented on Api/BccPay.Core.Shared/Converters/PhoneNumberConverter.cs
> +            return (prefix, normalizedNumber[prefixDigitsLength..]);
yes, but one more clarification in accordance with this - we should compare the given country code with a phone number prefix, am I right?

2021-07-28 08:48 UTC, tkristiansen commented on Api/BccPay.Core.Shared/Converters/PhoneNumberConverter.cs
> +            return (prefix, normalizedNumber[prefixDigitsLength..]);
Good question.. in general, it should be possible for a person from Germany to have a Norwegian phone number. So if the country code we are using is not specifically given for the phone number, we should not require that they match. If the phone number we receive is starting with either 00 or + and has a valid country prefix, we can use that and ignore the country code.

So the conclusion is probably that for the current functionality (where we expect the country prefix to be provided), we don't need to use the country code at all...

PS: All phone numbers in BCC Members, which will be the source for most systems using BCC Pay, have phone numbers with a country prefix.

2021-07-28 16:12 UTC, tkristiansen commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentAttemptCommand.cs
> +
We should make sure we don't start another attempt in parallel with a still active attempt (i.e. fail if the state of the current attempt is not failed / aborted)

2021-07-28 16:12 UTC, tkristiansen commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> -        public string Email { get; set; }
Did you discuss / consider pros and cons for having the person data on Payment versus on PaymentAttempt? I was thinking that we could store such details on the Payment and re-use it for all the attempts.. but haven't spent a lot of time considering if that would be an issue. 

I'm thinking that the details of the person that should pay is known when the payment is created. Especially if we map it from the contact, it will always be the same anyway. What do you think?

2021-07-28 16:12 UTC, tkristiansen commented on Api/BccPay.Core.Domain/Entities/Payment.cs
> +        public void DeactivateLastAttempt()
Maybe call this Abort or Cancel? And set the status to be Cancelled? I think this method should also fail if we are in a state other than Draft or Failed (based on the current enum statuses - maybe we will have further statuses later on, but my point is that we don't want to just deactivate it while it is pending or processing..)

2021-07-28 16:12 UTC, tkristiansen commented on Api/BccPay.Core.Domain/Entities/Payment.cs
> +        public void DeactivateLastAttempt()
Maybe call this Abort or Cancel? And set the status to be Cancelled? I think this method should also fail if we are in a state other than Draft or Failed (based on the current enum statuses - maybe we will have further statuses later on, but my point is that we don't want to just deactivate it while it is pending or processing..)

2021-07-28 16:13 UTC, tkristiansen commented on Api/BccPay.Core.Enums/PaymentStatus.cs
> +        WaitingForFee,
What is this status for?

2021-07-28 16:47 UTC, markiyanshvets commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> -        public string Email { get; set; }
We discuss it with Yuriy, and we believe that personal data should not be stored in payment DB (only ID), an attempt will have only "invoice data".
I think it would be good to make it simple, on creating payment we will take only PayerId, Currency, and Amount without any personal data and set the status to "Processing" (other - Pending, Closed, and Completed). The second stage - while creating an attempt, we will put data which is belongs to the payer (country, billings, etc.), if all data is valid and the payment provider gives us a positive response, we will set status in an attempt to "WaitingForFee", in accordance - "Rejected" (invalid data, card token, etc.) or "SuccessfullyPaid".
If data will be invalid for the payment provider it would be nice to have retry, the result of retry is primary checkout page (without autofill data), or a new attempt with an intermediate point.

As a result, we will have 2 endpoints and in the first stage:

```
{
"PaymentId": "7b04430d-9c40-4bd1-ad11-b9c301e9926a",
    "PayerId": "555",
    "CurrencyCode": "NOK",
    "Amount": 500,
    "Created": "2021-07-28T18:08:44.3956614",
    "Updated": null,
    "PaymentProgress": "Processing",
    "Attempts": null
    }
```

second 
```
"Attempts":         {
            "Id": "payments/7b04430d-9c40-4bd1-ad11-b9c301e9926a/attempts/805c0ff7-d17e-4376-a3aa-4c444bef3344",
            "PaymentAttemptId": "805c0ff7-d17e-4376-a3aa-4c444bef3344",
            "IsActive": true,
            "PaymentMethod": "NetsCreditCard",
            "Created": "2021-07-28T19:05:08.0986716",
            "PaymentStatus": "WaitingForFee",
            "PaymentIdForCheckoutForm": "0017000061018034777a332b3cfd2643",
            "CountryCode": "NOR"
        }
```

2021-07-28 17:15 UTC, markiyanshvets commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> -        public string Email { get; set; }
No, I did it badly. If the currency is not supported by the payment provider we will get a bad request and need to update the parent node (Payment) instead of an attempt. 
As I mentioned before, it would be nice to provide a list of supported currencies for each payment provider to choose in the second stage? (Nets supports only 6)

2021-07-28 18:35 UTC, tkristiansen commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> -        public string Email { get; set; }
Yes, we need to have selection of payment providers based on currency and country, so adding available currencies for a payment method will be required.

2021-07-29 14:38 UTC, markiyanshvets commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentRequest.cs
> +        public Guid PayerId { get; set; }
Currently no, I think. 
Changed.

2021-07-29 14:38 UTC, markiyanshvets commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentRequest.cs
> +        /// For Nets provider : Currency should always be specified using a 3-letter code (ISO-4217).
Resolved

2021-07-29 14:39 UTC, markiyanshvets commented on Api/BccPay.Core.Contracts/Requests/CreatePaymentRequest.cs
> +        public int Amount { get; set; }
Resolved

2021-07-29 14:41 UTC, markiyanshvets commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> +                // TODO: Depend on payment provider
For now, I'm using PaymentRequestDto, but as we discussed earlier, we need more providers to make it generic for all

2021-07-29 14:41 UTC, markiyanshvets commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentCommand.cs
> +                    .Matches(new Regex(@"^([0-9]{1,9})$"));
Done

2021-07-29 14:41 UTC, markiyanshvets commented on Api/BccPay.Core.Domain/Entities/Payment.cs
> +        public int Amount { get; set; }
done

2021-07-29 14:41 UTC, markiyanshvets commented on Api/BccPay.Core.Domain/Entities/Payment.cs
> +            Updated = DateTime.Now;
Fixed

2021-07-29 14:41 UTC, markiyanshvets commented on Api/BccPay.Core.Enums/PaymentMethod.cs
> +        CreditCard
Agree, done

2021-07-29 14:42 UTC, markiyanshvets commented on Api/BccPay.Core.Infrastructure/PaymentProviders/Implementations/CreditCardPaymentProvider.cs
> +    internal class CreditCardPaymentProvider : IPaymentProvider
done

2021-07-29 14:42 UTC, markiyanshvets commented on Api/BccPay.Core.Shared/Converters/PhoneNumberConverter.cs
> +            return (prefix, normalizedNumber[prefixDigitsLength..]);
This method has been changed

2021-07-29 14:46 UTC, markiyanshvets commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentAttemptCommand.cs
> +
Now it depends on attempts and looks like "One of the attempts is still active.", and if we want to start a new payment, we need to close the previous (maybe later we will add scheduler or bg-service which will monitor expiration time or etc.)

2021-07-29 14:48 UTC, markiyanshvets commented on Api/BccPay.Core.Domain/Entities/Payment.cs
> +        public void DeactivateLastAttempt()
Not relevant method, we need to discuss how a user can deactivate an attempt, or it will be manipulated only with webhooks.

2021-07-29 14:48 UTC, markiyanshvets commented on Api/BccPay.Core.Enums/PaymentStatus.cs
> +        WaitingForFee,
Reworked

2021-07-29 14:53 UTC, markiyanshvets commented
Docs, DB, Get Point
![1](https://user-images.githubusercontent.com/34346633/127514481-d88833d5-83e2-426f-852e-464a9946b304.png)
![2](https://user-images.githubusercontent.com/34346633/127514485-668ed553-4bef-4e8e-95b5-55effca91b1c.png)
![3](https://user-images.githubusercontent.com/34346633/127514487-fc1fc5d6-0b5b-4f2b-9df1-2b7657601171.png)
![4](https://user-images.githubusercontent.com/34346633/127514488-f769af4f-3360-48f8-a41e-ce77e4ba9508.png)

2021-07-29 21:06 UTC, tkristiansen approved these changes
Well done, @markiyanshvets 👍

2021-07-29 21:06 UTC, tkristiansen commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentAttemptCommand.cs
> +                PaymentStatus = providerResult.IsSuccessful ? AttemptStatus.WaitingForFee : AttemptStatus.Rejected,
This does not have to be changed now for the current PR, but just adding some feedback: I'm not understanding what WaitingForFee is. Maybe something specific for Nets?
I believe we need to be more flexible on the status returned from the attempt. E.g. when we are going to have BankTransfer as a payment method, there will be nothing to do externally and most likely the status will be "Pending" or so. So instead of having just IsSuccessful, I believe the provider should return the actual status. But as indicated above, this can be adjusted when we have more payment methods ready.

2021-07-30 06:03 UTC, yuriy-butkevych approved these changes

2021-07-30 08:47 UTC, markiyanshvets commented on Api/BccPay.Core.Cqrs/Commands/CreatePaymentAttemptCommand.cs
> +                PaymentStatus = providerResult.IsSuccessful ? AttemptStatus.WaitingForFee : AttemptStatus.Rejected,
A lot of thanks. 
Perhaps a more appropriate word for "WaitingForFee" is "Pending". After the payment provider gives a response I need to summarize the result and I think, it's simple and gives us information about what we needed. If we need more information about the status (like, why it is rejected - it will be stored in IStatusDetails). I think it will work fine with BankTransfer too, anyway, we can modify it

2021-07-30 08:48 UTC, merged